# Generated by Django 5.0.4 on 2024-05-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_central_contrato_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='nombre',
            new_name='nombreCentral',
        ),
    ]
