# Generated by Django 5.0.4 on 2024-05-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_nombre_central_nombrecentral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='nombreCentral',
            new_name='nombre',
        ),
    ]
