# Generated by Django 5.0.4 on 2024-05-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_nombrecentral_central_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='nombre',
            new_name='nombreCentral',
        ),
    ]
